# -*- coding: utf-8 -*-
"""condicao.basica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13tESCt95f7dIpx7uhw4YYVS7IIxmCnYa
"""

idade = int ( input("qual a sua idade:") )

if idade >=18:
  print("Permitido")
else:
  print("Não permitido")